apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
spec:
  replicas: 6
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      serviceAccountName: python-app-sa  # Ensure this service account exists in your cluster
      containers:
      - name: python-app
        image: sureshkcloud/python-app:v12
        ports:
        - containerPort: 5000

