apiVersion: v1
kind: Service
metadata:
  name: python-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
      # Optional: Kubernetes assigns a port if nodePort is not specified
      # nodePort: 30065  # You can specify a port or leave it out for automatic assignment
  selector:
    app: python-app

