apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: python-app-cluster-read
subjects:
- kind: ServiceAccount
  name: python-app-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: python-app-cluster-reader
  apiGroup: rbac.authorization.k8s.io

