apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: python-app-read
  namespace: default
subjects:
- kind: ServiceAccount
  name: python-app-sa
  namespace: default
roleRef:
  kind: Role
  name: python-app-reader
  apiGroup: rbac.authorization.k8s.io

